server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consort_group
    username: consort
    password: 2231251fsad1
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

kafka:
  bootstrap-servers: localhost:9092
  course-purchased: course-purchased-topic
  producer:
    enable: true


#Дает сам Payme логин и пароль
paycom:
  login: login
  password: password

#Дает сам Click token
click:
  secret-key: test-secret-key-20250527

user:
  service:
    url: http://localhost:8081

security:
  token: wUIBjx3G1C1Ee+eIXtt/zVIFkS40lhoan0HgHriNERBL08Vv2Bwb92is6gZUGEzANhMXulAPHD9li4TmKrdDoA==
  expiration: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha

  model-converters:
    pageable-converter:
      enabled: true
