server:
  port: 8086

spring:
  application:
    name: payment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consort_group
    username: consort
    password: 2231251fsad1
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

#Дает сам Payme логин и пароль
paycom:
  login: login
  password: password

click:
  secret-key: secret-key