server:
  port: 8086
  forward-headers-strategy: framework

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: payment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:consort-postgres}:${DB_PORT:5432}/${POSTGRES_DB:consort_group}}
    username: ${DB_USERNAME:${POSTGRES_USER:consort}}
    password: ${DB_PASSWORD:${POSTGRES_PASSWORD:consort}}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  # добавим стандартные настройки spring-kafka (если используешь Spring Kafka)
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:"consort-kafka:9092"}

# твои собственные свойства (оставил без изменений по ключам)
kafka:
  bootstrap-servers: kafka:9092
  course-purchased: course-purchased-topic
  producer:
    enable: true

paycom:
  login: login
  password: password

click:
  secret-key: test-secret-key-20250527

user:
  service:
    url: http://consort-user-service:8081

security:
  token: ${SECURITY_TOKEN}
  expiration: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://consort-eureka-service:8762/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${HOSTNAME}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha
    use-root-path: true
  model-converters:
    pageable-converter:
      enabled: true
