server:
  port: 8086

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: payment-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/consort_group
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

kafka:
  bootstrap-servers: kafka:9092
  course-purchased: course-purchased-topic
  producer:
    enable: true

paycom:
  login: login
  password: password

click:
  secret-key: test-secret-key-20250527

user:
  service:
    url: http://consort-user-service:8081

security:
  token: ${SECURITY_TOKEN}
  expiration: 3600000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service:8762/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha

  model-converters:
    pageable-converter:
      enabled: true
